In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
typa(a)

NameError: name 'typa' is not defined

In [7]:
type(a)

list

In [5]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
b = []
for ai in a:
    b.append(ai * 2)
b

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
x = np.array(a)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
L = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(2 * L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [14]:
2 * a + b

array([12, 24, 36])

In [15]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [16]:
np.log(b)

array([ 2.30258509,  2.99573227,  3.40119738])

In [17]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001])

In [18]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 * 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
len(b)

2

In [20]:
len(b[0])

3

In [22]:
b = np.array([[10, 20, 30, 40], [50, 60, 70, 80]]) # 2 * 4 array
print (b)

[[10 20 30 40]
 [50 60 70 80]]


In [23]:
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])   # 2 x 3 x 4 array
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [24]:
len(c)

2

In [25]:
len(c[0])

3

In [26]:
len(c[0][0])

4

In [27]:
print(a.ndim)
print(a.shape)

1
(3,)


In [28]:
print(b,ndim)
print(b.shape)

NameError: name 'ndim' is not defined

In [29]:
print(b.ndim)
print(b.shape)

2
(2, 4)


In [30]:
print(c.ndim)
print(c.shape)

3
(2, 3, 4)


In [31]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
a[0,0]

0

In [33]:
a[0,1]

1

In [34]:
a[-1,-1]

5

In [35]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
a[0, :]

array([0, 1, 2, 3])

In [37]:
a[:, 1]

array([1, 5])

In [38]:
a[1, 1]

5

In [39]:
a[1:, 1:]

array([[5, 6, 7]])

In [40]:
a[:2, :2]  

array([[0, 1],
       [4, 5]])

In [41]:
m = array([[ 0,  1,  2,  3,  4],
           [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])

NameError: name 'array' is not defined

In [42]:
m = array([[ 0,  1,  2,  3,  4],
           [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])
m

NameError: name 'array' is not defined

In [43]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
a[-1, -1]

7

In [45]:
a[-2, -2]

2

In [47]:
a[-1, 1]

5

In [48]:
a[1, 1]

5

In [50]:
len(m[0])

5

In [51]:
a[:, 2]

array([2, 6])

In [53]:
a[:, 3]

array([3, 7])

In [54]:
a[1, 3]

7

In [55]:
a[1, 1:]

array([5, 6, 7])

In [56]:
a[:, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [59]:
(m[2,4])

14

In [60]:
(m[1,1:3])

array([6, 7])

In [61]:
(m[1:,2])

array([ 7, 12])

In [62]:
(m[:2,3:])

array([[3, 4],
       [8, 9]])

In [63]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [64]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [65]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) * 10
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([ 0, 20, 40, 60, 80])

In [66]:
a = np.array([0, 1, 2, 3]) * 10
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([ 0,  0,  0,  0,  0,  0, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20])

In [67]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])