In [2]:
import numpy as np

In [3]:
x = np.arange(1, 1001)
y = np.arange(1001, 2001)

In [4]:
%%time
z = np.zeros_like(x)
for i in range(1000):
    z[i] = x[i] + y[i]

Wall time: 0 ns


In [5]:
z[:10]

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

In [6]:
%%time
z = x+y

Wall time: 0 ns


In [7]:
z[:10]

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [9]:
a == b

array([False,  True, False,  True], dtype=bool)

In [10]:
a >= b

array([False,  True,  True,  True], dtype=bool)

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [12]:
np.all(a == b)

False

In [13]:
np.all(a == c)

True

In [14]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [20]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.exp(x)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [23]:
x = np.arange(100)

In [24]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [27]:
x = np.arange(12).reshpae(3,4)
x

AttributeError: 'numpy.ndarray' object has no attribute 'reshpae'

In [28]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [30]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [31]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [32]:
x + y

array([1, 2, 3, 4, 5])

In [33]:
array([1,2,3,4,5])

NameError: name 'array' is not defined

In [34]:
array([1, 2, 3, 4, 5])

NameError: name 'array' is not defined

In [35]:
array([1, 2, 3, 4, 5])

NameError: name 'array' is not defined

In [36]:
from array import array

In [37]:
array([1,2,3,4,5])

TypeError: array() argument 1 must be a unicode character, not list

In [38]:
array([1])

TypeError: array() argument 1 must be a unicode character, not list

In [39]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [40]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [41]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [42]:
a = np.arange(0, 40, 10)[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [43]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [44]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [45]:
np.sum(x)

10

In [46]:
x.sum()

10

In [47]:
x = np.array([1, 3, 2]

SyntaxError: unexpected EOF while parsing (<ipython-input-47-a8a3d048b74d>, line 1)

In [48]:
x = np.array([1, 3, 2])

In [49]:
x.min()

1

In [50]:
x.max()

3

In [51]:
x.argmin()

0

In [52]:
x.argmax()

1

In [53]:
x = np.array([1, 2, 3, 1])

In [54]:
x.mean()

1.75

In [55]:
np.median(x)

1.5

In [56]:
np.all([True, True, False])

False

In [57]:
np.any([True, True, False])

True

In [58]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [59]:
np.any(a != 0)

False

In [60]:
np.all(a==a)

True

In [61]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [62]:
((a <= b) & (b <= c)).all()

True

In [63]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [64]:
x.sum()

6

In [65]:
x.sum(axis=0)

array([3, 3])

In [66]:
x.sum(axis=1)

array([2, 4])

In [67]:
a = np.tile(np.arange(1, 7), (5, 1))
a

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [68]:
x.argmax()

2

In [69]:
print(a.max())

6


In [70]:
a.argmax()

5

In [71]:
x.max()

2

In [72]:
a.max()

6

In [73]:
a.max()

6

In [74]:
a = np.array([[4, 3, 5], [1,2,1]])
a

array([[4, 3, 5],
       [1, 2, 1]])

In [75]:
np.sort(a)

array([[3, 4, 5],
       [1, 1, 2]])

In [76]:
np.sort(a, axis=0)

array([[1, 2, 1],
       [4, 3, 5]])

In [77]:
a.sort(axis=1)
a

array([[3, 4, 5],
       [1, 1, 2]])

In [78]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [79]:
a[j]

array([1, 2, 3, 4])

In [81]:
a = np.array([[1, 2, 3, 4 ], [46, 99, 100, 71], [81, 59, 90, 100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [82]:
np.sort(a)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [83]:
np.sort(a, axis=0)

array([[  1,   2,   3,   4],
       [ 46,  59,  90,  71],
       [ 81,  99, 100, 100]])

In [84]:
np.sort(a, axis=1)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])